# Feature extraction configuration

channels:
  - "Cz"
  - "T5"
  - "T6"
  - "O1"
  - "O2"

epoch_duration: 20  # seconds
sampling_rate: 250  # Hz

frequency_bands:
  delta: [1, 4]
  theta: [4, 8]
  alpha: [8, 13]
  beta: [13, 30]
  gamma: [30, 45]

preprocessing:
  resample_freq: 250
  lowpass_freq: 70
  highpass_freq: 1
  notch_freq: 50  # or 60, depending on your country
  notch_width: 2
  reference: "average"  # or "common" or ["M1", "M2"] for specific electrodes

features:
  time_domain:
    - "voltage_percentile_90"
    - "std_dev"
    - "kurtosis"
    - "skewness"
    - "peak_to_peak"
  
  frequency_domain:
    band_powers: true
    power_ratios:
      - "alpha_delta"
      - "theta_alpha"
      - "delta_theta"
      - "beta_alpha"
      - "gamma_beta"
